FROM python:3.6

RUN mkdir -p /opt/services/djangoapp/src
WORKDIR /opt/services/djangoapp/src

COPY requirements.dev.txt /opt/services/djangoapp/src/

RUN pip install -r requirements.dev.txt

EXPOSE 8000

CMD ["gunicorn", "--bind", ":8000", "sidon.wsgi:application"]
