# Generated by Django 2.2.5 on 2019-12-08 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='CWE',
            new_name='cwe',
        ),
    ]
