# Generated by Django 2.2.5 on 2019-12-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191208_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoncriteria',
            name='cwe_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
