# Generated by Django 2.2.5 on 2020-02-07 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('commonCriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CommonCriteria')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Scan')),
            ],
        ),
        migrations.AddField(
            model_name='scan',
            name='results',
            field=models.ManyToManyField(through='core.Result', to='core.CommonCriteria'),
        ),
    ]
