# Generated by Django 2.2.5 on 2020-02-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200207_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('scan', 'commonCriteria')},
        ),
    ]
