const GET_ALL_USER_LIST = 'GET_ALL_USER_LIST';
const GET_ALL_USER_LIST_SUCCESS = 'GET_ALL_USER_LIST_SUCCESS';
const GET_ALL_USER_LIST_ERROR = 'GET_ALL_USER_LIST_ERROR';

export {
  GET_ALL_USER_LIST,
  GET_ALL_USER_LIST_SUCCESS,
  GET_ALL_USER_LIST_ERROR,
};
